---
title: "ECo 602 - Analysis of Environmental Data"
subtitle: "Week 08 and 09 Reading Questions"
author: "Michael France Nelson"
date: "Fall 2020"
output:
  # pdf_document:
  #   toc: true
  #   number_sections: TRUE
  html_document:
    theme: readable
    css: !expr here::here("formatting", "css", "eco_602_2020.css")
    toc: TRUE
    # toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
options(knitr.duplicate.label = "allow")
require(rmd.utils)
require(mfn.teaching.utils)

# devtools::install_github("michaelfrancenelson/rmd.utils", force = TRUE)

```


```{r build_assignment_page, echo=FALSE, eval=FALSE}
source_dir  = here::here("assignments", "reading_questions", "reading_questions_week_08")
out_dir     = here::here("docs", "assignments", "eco_602", "reading_questions")
source_file = find_file("reading_questions_week_08", search_path = source_dir, extension = ".Rmd", recursive = FALSE)

dir.exists(source_dir)
dir.exists(out_dir)
file.exists(source_file)

# rmarkdown::render(source_file, output_dir = out_dir)


if (FALSE)
{
  build_moodle_xml_questions(
    question_source_files = find_file(".Rmd", search_path = file.path(source_dir, "moodle"), return_all = TRUE),
    assignment_name = "reading_questions_week_08",
    xml_output_path = here::here("docs", "moodle_quiz_questions"))
}

```



```{r build_doc, echo=FALSE, eval=FALSE}
require(rmd.utils)
source_dir  = here::here("assignments", "reading_questions", "reading_questions_week_08")

out_dir     = here::here("docs", "assignments", "eco_602", "reading_questions")
source_file = find_file("reading_questions_week_08", search_path = source_dir, extension = ".Rmd", recursive = FALSE)

dir.exists(source_dir)
dir.exists(out_dir)
file.exists(source_file)


require(rmd.utils)
require(here)

assn_base_name = "reading_questions_week_08"
assn_source_file = find_file("reading_questions_week_08.Rmd", extension = ".Rmd",exact_match = TRUE)
assn_source_dir = find_file(assn_base_name, directory = TRUE, search_path = here::here("assignments"))

assn_source_dir = dirname(assn_source_file)
assn_q_dir = file.path(assn_source_dir, "moodle")

dir.exists(assn_source_dir)
dir.exists(assn_q_dir)

question_source_files = find_file(
  "", search_path = file.path(assn_source_dir, "moodle"), 
  return_all = TRUE, extension = ".Rmd")

assn_dir_out    = here::here("docs", "assignments", "eco_602", "reading_questions")
assn_file_out = file.path(assn_dir_out, assn_base_name)


file.exists(assn_source_file)
file.exists(assn_dir_out)
file.exists(assn_file_out)

key_file_out = here::here(
  "docs", "answer_keys",
  sprintf("%s_answer_key", assn_base_name))
library(rmd.utils)
build_assignment_doc(
  assn_source_file,
  question_source_files,
  doc_target_file = assn_file_out,
  key_target_file = NULL)



rmarkdown::render(source_file, output_dir = out_dir)
```



# Readings

The reading questions this week are drawn from material in the readings:

- Bolker Ch. 9, sections 9.1 - 9.2
- Zuur Ch. 5.1 - 5.2

# Questions

