---
title: "ECo 634 - Analysis of Environmental Data Lab"
subtitle: "Simulation and Power Analysis"
author: "Michael France Nelson (adaped from Kevin McGarigal)"
date: "Fall 2020"
output:
  # pdf_document:
  #   toc: true
  #   number_sections: TRUE
  html_document:
    theme: readable
    css: !expr here::here("formatting", "css", "styles.css")
    toc: TRUE
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
require(here)
knitr::opts_chunk$set(echo = TRUE)

require(here)
require(rmd.utils)
require(mfn.teaching.utils)
knitr::opts_chunk$set(echo = TRUE)
```

```{r linear_function, echo = FALSE, eval=FALSE}
linear = function(x, y_int, slope) { return (y_int + x * slope)}
```

```{r linear_simulator_function, echo = FALSE}
linear_simulator = function(x, y_int, slope, st_dev)
{
  linear = function(x, y_int, slope) { return (y_int + x * slope)}
  return(rnorm(n = length(x), mean = linear(x, y_int, slope), sd = st_dev))
}
```

```{r linear_sim_fit_function}
linear_sim_fit = function(x, y_int, slope, st_dev)
{
  y_sim = linear_simulator(
    x = x,
    y_int = y_int,
    slope = slope,
    st_dev = st_dev
  )
  return(lm(y_sim ~ x))
}
```





```{r pop_sd_simulation echo = FALSE, eval = FALSE}
alpha = 0.05
n_sims = 10
p_vals = numeric(n_sims)
sd_obs
n_sds = 50
pop_sds = seq(from = 0.1, to = 1.5, length.out = n_sds)
pop_sd_power = numeric(length(pop_sds))

for(j in 1:length(pop_sds))
{
  pop_sd_j = pop_sds[j]
  for(i in 1:n_sims)
  {
    fit_sim = linear_sim_fit(
      x = birdhab$ls,
      y_int = int_obs,
      slope = slope_obs,
      st_dev = pop_sd_j
    )
    
    p_vals[i] = summary(fit_sim)$coefficients[2, 'Pr(>|t|)']
  }
  pop_sd_power[j] = sum(p_vals < alpha) / n_sims
}

plot(pop_sds, pop_sd_power, type = 'l', xlab = 'Population Standard Deviation', ylab = 'Power')
abline(v = sd_obs, lty = 2, col = 'red')

```

```{r dispersion_sample_size_template, echo=TRUE, eval=FALSE}
alpha = 0.05
n_sims = 100
p_vals = ...
n_sds = 10
# you can use the values you chose in the last simulation as a guide for what to choose here
pop_sds = seq(...) 

# These were the sample sizes in the walkthrough simulation.  you may want to try a different range.
sample_sizes = seq(10, 50)

sim_output_3 = matrix(nrow = length(pop_sds), ncol = length(sample_sizes))

for(k in 1:length(pop_sds))
{
  pop_sd_k = pop_sds[k]
  for(j in 1:length(sample_sizes))
  {
    x_vals = ...
    
    for(i in 1:n_sims)
    {
      fit_sim = linear_sim_fit(...)
      p_vals[i] = summary(fit_sim)$coefficients[2, 'Pr(>|t|)']
    }
    sim_output_3[k, j] = sum(p_vals < alpha) / n_sims
  }
}
image(sim_output_3)
```





```{r sd_size_sim_2, echo=FALSE, eval = FALSE}
alpha = 0.05
n_sims = 50
p_vals = numeric(n_sims)
n_sds = 10
pop_sds = seq(from = 0.1, to = 1.5, length.out = n_sds)
sample_sizes = seq(10, 50)

sim_output_3 = matrix(nrow = length(pop_sds), ncol = length(sample_sizes))

for(k in 1:length(pop_sds))
{
  pop_sd_k = pop_sds[k]
  for(j in 1:length(sample_sizes))
  {
    x_vals = seq(0, 100, length.out = sample_sizes[j])
    
    for(i in 1:n_sims)
    {
      fit_sim = linear_sim_fit(
        x = x_vals,
        y_int = int_obs,
        slope = slope_obs,
        st_dev = pop_sd_k
      )
      p_vals[i] = summary(fit_sim)$coefficients[2, 'Pr(>|t|)']
    }
    sim_output_3[k, j] = sum(p_vals < alpha) / n_sims
  }
}
image(sim_output_3)
contour(
  x = pop_sds,
  y = sample_sizes, 
  z = sim_output_3,
  xlab = "population s.d.",
  ylab = "sample size",
  main = "Contour Plot of Statistical Power")
rgl::persp3d(
  x = pop_sds,
  y = sample_sizes, 
  z = sim_output_3,
  col = 'lightblue',
  theta = 30, phi = 30, expand = .75,
  ticktype = 'detailed')
```


```{r persp_plot_interactive_2, echo = FALSE, eval = FALSE}
rgl::persp3d(
  x = pop_sds,
  y = sample_sizes, 
  z = sim_output_3,
  col = 'lightblue',
  theta = 30, phi = 30, expand = .75,
  ticktype = 'detailed')
```
```{r contour_plot_2, echo=FALSE, eval = FALSE}
contour(
  x = pop_sds,
  y = sample_sizes, 
  z = sim_output_3,
  xlab = "population s.d.",
  ylab = "sample size",
  main = "Contour Plot of Statistical Power")
```
