---
title: "ECo 634 - Analysis of Environmental Data Lab"
subtitle: "Simulation and Power Analysis - Custom Functions"
author: "Michael France Nelson (adaped from Kevin McGarigal)"
date: "Fall 2020"
output:
  html_document:
    theme: readable
    css: !expr here::here("formatting", "css", "styles.css")
    toc: TRUE
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
require(here)
knitr::opts_chunk$set(echo = TRUE)

require(here)
require(rmd.utils)
require(mfn.teaching.utils)
knitr::opts_chunk$set(echo = TRUE)
```

```{r read_bird_data, echo = FALSE}
birds = read.csv(here::here("data", "bird.sub.csv"), header = TRUE)
hab = read.csv(here::here("data", "hab.sub.csv"), header = TRUE)
birdhab = merge(hab, birds, by = c('basin', 'sub'))

birdhab$ls

```

```{r n_dat, echo = FALSE}
sim_sample_size = read.csv(here::here(
  "data", "lab_11", "sim_output_sample_size_1000.csv"))

here::here(
  "data", "lab_11", "sim_output_sample_size_1000_p_005.csv")
sim_sample_size_01 = read.csv(here::here(
  "data", "lab_11", "sim_output_sample_size_1000_p_01.csv"))
sim_sample_size_005 = read.csv(here::here(
  "data", "lab_11", "sim_output_sample_size_1000_p_005.csv"))


plot(power ~ sample_size, data = sim_sample_size, type = "l", xlim = c(0, 100))
points(power ~ sample_size, data = sim_sample_size_01, type = "l")
points(power ~ sample_size, data = sim_sample_size_005, type = "l")

# sample_size_powers = sim_sample_size$power
# sample_sizes = sim_sample_size$sample_size
```

```{r effect_size_dat, echo = FALSE}
sim_effect_size = read.csv(here::here(
  "data", "lab_11", "sim_output_effect_size_1000_200.csv"))
# effect_powers = sim_effect_size$power
# effect_sizes = sim_effect_size$effect_size
```

```{r n_effect_size_dat, echo = FALSE}
# rm(list = ls())
load(
  file = here::here(
    "data", "lab_11",
    "sim_n_effect_size_1000_200.RData"))
```

```{r dispersion_n_dat, echo = FALSE}
# rm(list = ls())
load(
  file = here::here(
    "data", "lab_11",
    "sim_output_dispersion_n_1000.RData"))
# "sim_output_sample_size_effect_size_1000_200_2.RData"))

# effect_sample_sizes_powers = sim_3_dat$power
# pop_sd       = sim_3_dat$pop_sd
# sample_sizes = sim_3_dat$sample_size
```

```{r dispersion_dat, echo = FALSE}
dat_dispersion_sim = 
  read.csv(
    here::here(
      "data", "lab_11",
      "sim_output_dispersion_1000_200.csv"))
```



```{r smoothing, eval = FALSE, echo = FALSE}

library(mgcv)

n_pts = 50

aa = within(
  sim_n_effect_size,
  {
    pred_dat = expand.grid(
      x_beta = effect_size, 
      x_n = sample_size)
    x_beta = matrix(
      effect_size, 
      nrow = nrow(power), ncol = ncol(power), byrow = F)
    x_n    = matrix(
      sample_size, 
      nrow = nrow(power), ncol = ncol(power), byrow = T)
    # fit_1 = mgcv::gam(c(power) ~ te(c(x_beta), c(x_n)))
    # fit_z_1 = predict(fit_1, pred_dat)
    fit_2 = loess(
      c(power) ~ c(x_beta) + c(x_n), span = n_pts / length(power))
    fit_z_2 = predict(fit_2, pred_dat)
  })


head(sim_effect_size)
sim_beta = within(
  as.list(sim_effect_size),
  {
    fit = loess(power ~ effect_size, span = 0.1)
    pred = predict(fit, effect_size)
    plot(power ~ effect_size, type = "l")
    points(pred ~ effect_size, type = "l", col = 2)
  }
)

with(
  sim_beta,
  {
    plot(power ~ effect_size, type = "l")
    # plot(power ~ pred_1, type = "l")
    points(pred ~ effect_size, type = "l", col = 2)
  }
)


predict(fit_l, sim_effect_size$effect_size)

loess()

with(
  aa,
  rgl::persp3d(
    x = effect_size, y = sample_size, z = power, 
    alpha = 0.2, color = "red")
)

with(
  aa,
  rgl::persp3d(
    x = effect_size, y = sample_size, z = fit_z_1, 
    alpha = 0.2, color = "steelblue", add = T)
)

with(
  aa,
  rgl::persp3d(
    x = effect_size, y = sample_size, z = fit_z_2, 
    alpha = 0.2, color = "green", add = T)
)


rgl::persp3d(x = aa$effect_size, y = aa$sample_size, z = aa$fit_z_1, alpha = 0.2, add = T, color = "steelblue")

rgl::persp3d(x = aa$effect_size, y = aa$sample_size, z = aa$fit_z_2, alpha = 0.2, add = F, color = "green")

predict(aaa$fit_1, expand.grid(x_beta = aaa$x_beta, x_n = aaa$x_n))
mgcv::predict.gam()

loess()
aa$
  
  x <- rnorm(200)
y <- rnorm(200)
z <- rnorm(200)

tab <- data.frame(x,y,z)

mod <- mgcv::gam(z ~ te(x, y), data = tab)
grid <- -5:5
rgl::persp3d(grid, grid, zfit)


```

