---
title: "ECo 602 - Analysis of Environmental Data"
subtitle: "Week 07 Reading Questions"
author: "Michael France Nelson"
date: "Fall 2020"
output:
  # pdf_document:
  #   toc: true
  #   number_sections: TRUE
  html_document:
    theme: readable
    css: !expr here::here("formatting", "css", "eco_602_2020.css")
    toc: TRUE
    # toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
options(knitr.duplicate.label = "allow")
require(rmd.utils)
require(mfn.teaching.utils)

# devtools::install_github("michaelfrancenelson/rmd.utils", force = TRUE)

```

```{r build_assignment_page, echo=FALSE, eval=FALSE}
source_dir  = here::here("assignments", "reading_questions", "week_07")
out_dir     = here::here("docs", "assignments", "eco_602", "reading_questions")
source_file = find_file("602_week_07_reading", search_path = source_dir, extension = ".Rmd")

dir.exists(source_dir)
dir.exists(out_dir)
file.exists(source_file)

rmarkdown::render(source_file, output_dir = out_dir)


if (FALSE)
{
  build_moodle_xml_questions(
    question_source_files = find_file(".Rmd", search_path = file.path(source_dir, "moodle"), return_all = TRUE),
    assignment_name = "reading_questions_week_07",
    xml_output_path = here::here("docs", "moodle_quiz_questions"))
}

```




# Readings

The reading questions this week are drawn from material in the readings:

- McGarigal Ch 6, 7.

# Questions



<!-- ```{r moodle_questions, results='hide', echo=FALSE} -->

<!-- assgn_dir = here::here("assignments", "reading_questions", "week_07", "moodle") -->
<!-- dir.exists(assgn_dir) -->

<!-- question_source_files = find_file( -->
<!--   ".Rmd", -->
<!--   search_path = assgn_dir, -->
<!--   return_all = TRUE) -->



<!-- tmp = add_moodle_quiz_questions( -->
<!--   question_source_files,  -->
<!--   include_solution = FALSE,  -->
<!--   include_metadata = FALSE) -->
<!-- tmp -->

<!-- ``` -->
