---
title: "ECo 602 - Analysis of Environmental Data"
subtitle: "Group 1: General Linear Models"
author: "Michael France Nelson"
date: "Fall 2020"
output:
  beamer_presentation:
    pandoc_args: !expr paste0(here::here("formatting", "beamer", "eco_602_2020_beamer.yaml"))
    highlight: tango
    # theme: "default"
    colortheme: "spruce"
    fonttheme: "serif"
    slide_level: 2
    incremental: false
classoption: t
header-includes:
  \usepackage{animate}
  \input{`r here::here("formatting", "beamer", "eco_602_2020_headers_tikz.tex")`}
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(rmd.utils)
require(mfn.teaching.utils)
require(ggplot2)
options(knitr.duplicate.label = "allow")

# devtools::install_github("michaelfrancenelson/rmd.utils", force = TRUE)

```


```{r build_slides, echo=FALSE, eval=FALSE}
require(rmd.utils)
source_dir  = here::here("course_docs", "lectures", "602", "week_09")
out_dir     = here::here("docs", "lecture_notes")
source_file = find_file("week_09_2", search_path = source_dir, extension = ".Rmd")

dir.exists(source_dir)
dir.exists(out_dir)
file.exists(source_file)

rmarkdown::render(source_file, output_dir = out_dir)
```



## Key Concepts

- What makes a model linear?
- Categorical and continuous predictors.
- Key assumptions of general linear models.




```{r group_1_slides, child = find_file("group_1_general_linear_models_penguins.Rmd")}
```




## Key Concepts

- What makes a model linear?
- Categorical and continuous predictors.
- Key assumptions of general linear models.
