---
title: "ECo 634 - Analysis of Environmental Data Lab"
subtitle: "Filesystems Assignment"
author: "Michael France Nelson"
date: "Fall 2020"
output:
  # pdf_document:
  #   toc: true
  #   number_sections: TRUE
  html_document:
    theme: readable
    css: !expr here::here("formatting", "css", "eco_602_2020.css")
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(fs)
require(data.tree)
require(here)
```


```{r}
requireNamespace("fs")
loadNamespace("fs")
attachNamespace("fs")

aaa = function (path = ".", recurse = TRUE, ...) 
{
  files <- dir_ls(path, recurse = recurse, ...)
  by_dir <- split(files, path_dir(files))
  ch <- fs:::box_chars()
  get_coloured_name <- function(x) {
    coloured <- fs:::colourise_fs_path(x)
    sub(x, path_file(x), coloured, fixed = TRUE)
  }
  print_leaf <- function(x, indent) {
    leafs <- by_dir[[x]]
    for (i in seq_along(leafs)) {
      if (i == length(leafs)) {
        cat(indent, fs:::pc(ch$l, ch$h, ch$h, " "), 
            get_coloured_name(leafs[[i]]), "\n", 
            sep = "")
        print_leaf(leafs[[i]], paste0(indent, "    "))
      }
      else {
        cat(indent, fs:::pc(ch$j, ch$h, ch$h, " "), 
            get_coloured_name(leafs[[i]]), "\n", 
            sep = "")
        print_leaf(leafs[[i]], paste0(indent, pc(ch$v, 
                                                 "   ")))
      }
    }
  }
  
  print_leaf_2 <- function(x, indent) {
    out = c()
    leafs <- by_dir[[x]]
    for (i in seq_along(leafs)) {
      if (i == length(leafs)) {
        out = c(out,
                paste(indent, fs:::pc(ch$l, ch$h, ch$h, " "),
                      get_coloured_name(leafs[[i]]), "\n", 
                      sep = ""),
                # )
                # out = c(out, 
                paste0(leafs[[i]], paste0(indent, "    "))
        )
      }
      else {
        out = c(out,
                paste(indent, fs:::pc(ch$j, ch$h, ch$h, " "), 
                      get_coloured_name(leafs[[i]]), "\n", 
                      sep = ""),
                paste0(leafs[[i]], paste0(indent, pc(ch$v, 
                                                     "   "))))
      }
    }
    return(out)
  }
  # cat(fs:::colourise_fs_path(path), "\n", sep = "")
  # print_leaf(path_expand(path), "")
  # print(fs:::colourise_fs_path(path))
  # invisible(files)
  # return(fs:::colourise_fs_path(path))
  return(print_leaf_2(path_expand(path), ""))
}


aaa(search_path)


colorize_fs_path = 
  function (x, ..., colors = Sys.getenv("LS_COLORS", gnu_ls_defaults)) 
  {
    if (length(x) == 0 || !has_color() || !nzchar(colors)) {
      return(x)
    }
    perms <- try(file_info(x)$permissions, silent = TRUE)
    if (inherits(perms, "try-error")) {
      return(x)
    }
    vals <- strsplit(colors, ":")[[1]]
    nms <- strsplit(vals, "=")
    if (!(length(vals) == length(nms) && all(lengths(nms) == 
                                             2))) {
      return(x)
    }
    map <- setNames(vapply(nms, `[[`, character(1), 2), 
                    vapply(nms, `[[`, character(1), 1))
    file_types <- map[grepl("^[*][.]", names(map))]
    names(file_types) <- sub("^[*][.]", "", names(file_types))
    res <- character(length(x))
    for (i in seq_along(x)) {
      code <- map[.Call(fs_file_code_, x[[i]], as.integer(perms[[i]]))]
      if (is.na(code)) {
        code <- file_types[na.omit(tools::file_ext(x[[i]]))]
      }
      if (length(code) > 0 && !is.na(code)) {
        res[[i]] <- paste0("\033[", code, "m", 
                           x[[i]], "\033[0m")
      }
      else {
        res[[i]] <- x[[i]]
      }
    }
    res
  }

dir_tree_2 = function (path = ".", recurse = TRUE, ...) 
{
  box_chars = 
    function () 
    {
      if (is_utf8_output()) {
        list(h = "─", v = "│", l = "└", 
             j = "├")
      }
      else {
        list(h = "-", v = "|", l = "\\", j = "+")
      }
    }
  pc <- 
    function (...) 
    {
      paste0(..., collapse = "")
    }
  dir_ls = fs:::dir_ls
  # colourise_fs_path <- fs:::colourise_fs_path
  colourise_fs_path <- colorize_fs_path
  
  files <- dir_ls(path, recurse = TRUE)
  # files <- dir_ls(path, recurse = recurse, ...)
  by_dir <- split(files, path_dir(files))
  ch <- box_chars()
  get_coloured_name <- function(x) {
    coloured <- colourise_fs_path(x)
    sub(x, path_file(x), coloured, fixed = TRUE)
  }
  
  x = path.expand(path)
  get_leaf = function(x, indent){
    leafs <- by_dir[[x]]
    out = c()
    for(i in seq_along(leafs))
    {
      if (i == length(leafs)) {
        #     cat(indent, pc(ch$l, ch$h, ch$h, " "), 
        #         get_coloured_name(leafs[[i]]), "\n", 
        #         sep = "")
        #     print_leaf(leafs[[i]], paste0(indent, "    "))
        #   }          
      }
    }
    
    print_leaf <- function(x, indent) {
      leafs <- by_dir[[x]]
      # for (i in seq_along(leafs)) {
      #   if (i == length(leafs)) {
      #     cat(indent, pc(ch$l, ch$h, ch$h, " "), 
      #         get_coloured_name(leafs[[i]]), "\n", 
      #         sep = "")
      #     print_leaf(leafs[[i]], paste0(indent, "    "))
      #   }
      #   else {
      #     cat(indent, pc(ch$j, ch$h, ch$h, " "), 
      #         get_coloured_name(leafs[[i]]), "\n", 
      #         sep = "")
      #     print_leaf(leafs[[i]], paste0(indent, pc(ch$v, 
      #                                              "   ")))
      #   }
      # }
      print(leafs)
    }
    
    
    print_leaf_2 <- function(x, indent) {
      leafs <- by_dir[[x]]
      for (i in seq_along(leafs)) 
      {
        # print(paste0("i = ", i))
        if (i == length(leafs)) 
        {
          cat(indent, pc(ch$l, ch$h, ch$h, " "), 
              get_coloured_name(leafs[[i]]), "\n", 
              sep = "")
          print_leaf(leafs[[i]], paste0(indent, "    "))
        }
        else 
        {
          # print("else clause: ")
          cat(indent, pc(ch$j, ch$h, ch$h, " "), 
              get_coloured_name(leafs[[i]]), "\n", 
              sep = "")
          print_leaf(leafs[[i]], paste0(indent, pc(ch$v, 
                                                   "   ")))
        }
      }
    }
    cat(colourise_fs_path(path), "\n", sep = "")
    print_leaf(path_expand(path), "")
    # print_leaf_2(path_expand(path), "")
    invisible(files)
  }
  
  dir_tree_2(search_path)
  dir_tree(search_path)
}

```


```{r eval = FALSE, include = FALSE}
search_path = here::here("assignments", "common", "example_structure")
path_df = data.frame(pathString = paste0("/", list.files(search_path, recursive = TRUE)))




cat(fs:::colourise_fs_path(search_path))
crayon:::multicol(fs:::colourise_fs_path(search_path))

fs:::path_tidy(search_path)
fs:::print.fs_path(search_path)


fs_path(search_path)
fs:::fs_path(search_path)
fs:::print.fs_path()

as_fs_path(path_df)

capture.output(dir_tree(search_path), file = "aaa.txt")

fs::dir_tree(search_path)
print(fs::dir_tree(search_path))
require(fs)
fs::as_fs_path()
```



```{r comment="", eval = FALSE}

# list.files(path = here("assignments", "common", "example_structure"), recursive = T)
# here()
writeLines(fs::dir_tree(path = here("assignments", "common", "example_structure")), con = "aaa.txt")
fs::dir_tree(path = here("assignments", "common", "example_structure"))
example_dir_struct = fs::dir_tree(path = here("assignments", "common", "example_structure"))


fs::dir_tree(readLines("aaa.txt"))


search_path = here("assignments", "common", "example_structure")
fs::dir_tree(search_path)



path_df = data.frame(pathString = paste0("/", list.files(search_path, recursive = TRUE)))


path_data_tree = data.tree::as.Node(path_df)




print(path_data_tree)

# example_dir_struct
# print(example_dir_struct)
# str(fs::dir_tree(path = here("assignments", "common", "example_structure")))
```


```{r}
# devtools::install_github("stla/dir2json")
```

https://stackoverflow.com/questions/18908708/installing-ruby-gem-in-windows
https://github.com/emad-elsaid/dirtree


# 