---
title: "flipper length hypotheses"
output:  
  html_document:
    theme: readable
    css: !expr here::here("formatting", "css", "styles.css")
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
editor_options: 
  chunk_output_type: console
---


Question
========

```{r CSS, echo = FALSE, results = "asis"}

cat(readLines(here::here("formatting", "css", "styles.css")))
require(palmerpenguins, quietly = TRUE)
```

<div class="instructionsborder">

#### Instructions

- Consider the alternative and null hypothesis for a two-sample test of the difference in mean flipper length between the two two penguin species.

</div>

<div class="questionborder">

### Q1 1 pt. (short answer)

- State the null hypothesis of a two-sample test for the difference in mean flipper lengths between the two penguin species.

</div>

Solution
========

### Grading Guide

A possible answer:

- "There is no difference in mean flipper length of Adele and Chinstrap penguins."

The students might also propose a 1-sided hypothesis:

- "Mean flipper length is higher in Adelie than Chinstrap penguins (or vice-versa)." 


Meta-information
================
extitle: flipper length hypotheses

extype: string

exsolution: nil

exname: lab_08
exsection: lab_08

exextra[essay,logical]: TRUE
exextra[essay_format,character]: editor
exextra[essay_required,logical]: TRUE
exextra[essay_fieldlines,numeric]: 15

expoints: 1

