---
title: "[ECo 602 - Analysis of Environmental Data](/eco_602_634_2020/index.html){target='_blank'}"
subtitle: "Setting up RStudio to work with Git"
author: "Michael France Nelson"
date: "Fall 2020"
output:
  # pdf_document:
  #   toc: true
  #   number_sections: TRUE
  html_document:
    theme: readable
    css: !expr here::here("formatting", "css", "eco_602_2020.css")
    toc: TRUE
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)

```




```{r build_assignment_page, eval=FALSE, include=FALSE}
require(rmd.utils)

assn_base_name = "eco_602_final_proj"
assn_source_file = find_file("eco_602_final_proj.Rmd", extension = ".Rmd")
assn_source_dir = dirname(assn_source_file)

assn_dir_out    = here::here("docs", "assignments", "eco_602", "individual")
assn_file_out = file.path(assn_dir_out, assn_base_name)

file.exists(assn_source_file)
file.exists(assn_source_dir)
file.exists(assn_dir_out)
file.exists(assn_file_out)

rmarkdown::render(
  input = assn_source_file, 
  output_dir = assn_dir_out)

```


I


# Links

https://support.rstudio.com/hc/en-us/articles/200532077?version=1.3.1073&mode=desktop




# Connecting RStudio Cloud and GitHub

Some [hopefully] helpful links:

https://github.com/forestgeo/learn/issues/75