---
title: "ECo 602 - Analysis of Environmental Data"
subtitle: "Frequentist Confidence Intervals"
author: "Michael France Nelson"
date: "Fall 2020"
output:
    beamer_presentation:
    pandoc_args: !expr paste0(here::here("formatting", "beamer", "eco_602_2020_beamer.yaml"))
    highlight: tango
    # theme: "default"
    colortheme: "spruce"
    fonttheme: "serif"
    slide_level: 2
    incremental: false
classoption: t
header-includes:
  \input{`r here::here("formatting", "beamer", "eco_602_2020_headers_tikz.tex")`}
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
require(rmd.utils)
require(mfn.teaching.utils)
require(ggplot2)
require(latex2exp)

# devtools::install_github("michaelfrancenelson/mfn.teaching.utils", force = TRUE)
# devtools::install_github("michaelfrancenelson/rmd.utils", force = TRUE)

figure_dir =
  file.path(
    find_file(
      "confidence_intervals",
      directory = TRUE),
    "figures")
```



# Simulated confidence intervals

```{r eval = FALSE}

set.seed(1234)

for (i in 1:5)
{
  
  png(filename = file.path(
    figure_dir,
    sprintf("simulated_conf_intervals_wide_1800_300_%0.2d.png", i)), 
    res = 170, width = 1800, height = 300, bg = "transparent")
  
  print(
    ggplot(
      simulated_confidence_intervals_of_mean(
        alpha = 0.05, n_samples = 20, n_intervals = 100),
      aes(x = simulation, colour = in_sample_ci)) +
      geom_point(aes(y = sample_mean), show.legend = FALSE) +
      geom_segment(
        aes(xend = simulation, y = lower_t, yend = upper_t), show.legend = FALSE) +
      geom_hline(yintercept = 0, lty = 2) + xlab("") + ylab("") +
      theme_void() 
    # ggtitle("100 simulated 95% confidence intervals"))
  )
   dev.off()
}

```



# Standard Normal standard deviation interpretation
```{r eval = FALSE}
plot_norm_tails

fill_upper = rgb(0, 0.3, 0.8, 0.25)
fill_lower = rgb(0, 0.3, 0.8, 0.25)
fill_middle = rgb(0, 0, 0, 0)

fill_middle = rgb(0, 0.3, 0.8, 0.25)
fill_upper = rgb(0, 0, 0, 0)
fill_lower = rgb(0, 0, 0, 0)

norm_dat = build_dnorm_dat(-3, 3, 1000, 0, 1)
two_sd_dat = build_tail_dat(norm_dat, lower_x = -2, upper_x = 2)
one_sd_dat = build_tail_dat(norm_dat, lower_x = -1, upper_x = 1)
gg_ribbons_two = build_ribbons(two_sd_dat, fill_upper = fill_upper, fill_middle = fill_middle, fill_lower = fill_lower)
gg_ribbons_one = build_ribbons(one_sd_dat, fill_upper = fill_upper, fill_middle = fill_middle, fill_lower = fill_lower)

png(filename = file.path(figure_dir,"standard_normal_standard_deviation_interpretation.png"), res = 240, width = 2000, height = 900)
ggplot(norm_dat) +
  geom_line(aes(x, y1)) + 
  gg_ribbons_one$middle + 
  gg_ribbons_two$middle +
  ylab("f(z)") + xlab("z")
dev.off()

```




# Sample and sampling distributions


```{r, eval = FALSE}
pois_sample_fmt = "Sample of %d individuals\nmean = %0.4s, var = %0.4s"
pois_pop_fmt = "A Poisson-distributed population\nmean = %0.4s, var = %0.4s"

lmbda = 4.5
n_pop = 10000

x_lab = "eggs per nest"

sample_pois_mean = function(n_sims, n_samps)
{
  out = c()
  for (i in 1:n_sims)
    out = c(out, mean(sample(pop_poisson, n_samps, replace = TRUE)))
  return(out)
}

hh = function(x, x_lim =  c(mean(pop_poisson) - 2, mean(pop_poisson) + 2), n_sims = 1500)
{
  hist(
    sample_pois_mean(n_sims, x),
    main = sprintf(sampling_dist_of_mean_fmt, x),
    xlim = x_lim, xlab = x_lab, ylab = ylab, 
    axes = FALSE, freq = FALSE)
  axis(1)
}


h_samp = function(n)
{
  samp1 = sample(pop_poisson, n, replace = TRUE)
  hist(samp1,
       main = sprintf(
         pois_sample_fmt,
         n, mean(samp1), var(samp1)), xlab = x_lab,
       freq = FALSE)
}


sampling_dist_of_mean_fmt = "Sampling distribiution of the mean\nn = %s"
pois_sample_fmt = "Sample of %d individuals"
pois_pop_fmt = "A Poisson-distributed population\nmean = %0.4s, var = %0.4s"


set.seed(100)
pop_poisson = rpois(n_pop, lmbda)

png(filename = file.path(figure_dir,"population_sample_sampling_distributions.png"), res = 170, width = 1800, height = 1000)
{
  par(mfrow = c(2, 3))
  hist(pop_poisson, main = "Poisson-distributed population", xlab = x_lab, freq = FALSE)
  h_samp(500)
  h_samp(100)
  hh(50, x_lim = c(mean(pop_poisson) - 1.5, mean(pop_poisson) + 1.5))
  hh(100, x_lim = c(mean(pop_poisson) - 1.5, mean(pop_poisson) + 1.5))
  hh(500, x_lim = c(mean(pop_poisson) - 1.5, mean(pop_poisson) + 1.5))
}
dev.off()


```


# Standardizing penguin flippers

```{r, eval = FALSE}
require(palmerpenguins)

penguins_dt = data.table(penguins)

dat = penguins_dt[species == "Chinstrap", ]
dat[, flipper_centered := flipper_length_mm - mean(flipper_length_mm)]
dat[, flipper_standardized := flipper_centered / sd(flipper_length_mm)]

bks = 11
bks_1 = dat[, seq(min(flipper_length_mm), max(flipper_length_mm), length.out = bks)]
bks_2 = dat[, seq(min(flipper_centered), max(flipper_centered), length.out = bks)]
bks_3 = dat[, seq(min(flipper_standardized), max(flipper_standardized), length.out = bks)]


sd(dat$flipper_length_mm)
sd(dat$flipper_centered)
sd(dat$flipper_standardized)

mean(dat$flipper_length_mm)
mean(dat$flipper_centered)
mean(dat$flipper_standardized)


mean(dat$flipper_length_mm)
sd(dat$flipper_length_mm)


frq = TRUE
if (FALSE)
{
  png(filename = file.path(figure_dir,"chinstrap_penguins_flipper_lengths_center_standardize.png"), res = 190, width = 1800, height = 550)
  par(mfrow = c(1, 3))
  hist(
    dat$flipper_length_mm, 
    main = "Chinstrap Penguins\nHistogram of Flipper Length",
    freq = frq,
    xlab = "fliper length (mm)",
    breaks = bks_1)
  
  hist(
    dat$flipper_centered, 
    main = "Chinstrap Penguins\nCentered Flipper Length",
    freq = frq,
    xlab = "fliper length (mm)",
    breaks = bks_2)
  
  hist(
    dat$flipper_standardized, 
    main = "Chinstrap Penguins\nStandardized Flipper Length",
    freq = frq,
    xlab = "fliper length (mm)",
    breaks = bks_3)
  dev.off()
}



mean(dat$flipper_length_mm)

frq = TRUE
{
  png(filename = file.path(figure_dir,"chinstrap_penguins_flipper_lengths_center_standardize.png"), res = 190, width = 1800, height = 550)
  par(mar = par("mar") + c(5, 0, 0, 0))
  par(mfrow = c(1, 3))
  hist(
    dat$flipper_length_mm, 
    main = "Chinstrap Penguins\nHistogram of Flipper Length",
    freq = frq,
    xlab = "fliper length (mm)",
    breaks = bks_1)
  mtext(
    sprintf(
      "mean flipper length: %0.2f",
      mean(dat$flipper_length_mm)),
    side = 1, line = 5)
  mtext(
    sprintf(
      "fipper length standard deviation: %0.2f",
      sd(dat$flipper_length_mm)),
    side = 1, line = 7)
  
  curve(dnorm(x, ))
  
  hist(
    dat$flipper_centered, 
    main = "Chinstrap Penguins\nCentered Flipper Length",
    freq = frq,
    xlab = "fliper length (mm)",
    breaks = bks_2)
  mtext(
    sprintf(
      "mean flipper length: %0.2f",
      mean(dat$flipper_centered)),
    side = 1, line = 5)
  mtext(
    sprintf(
      "fipper length standard deviation: %0.2f",
      sd(dat$flipper_centered)),
    side = 1, line = 7)
  
  hist(
    dat$flipper_standardized, 
    main = "Chinstrap Penguins\nStandardized Flipper Length",
    freq = frq,
    xlab = "fliper length (mm)",
    breaks = bks_3)
  mtext(
    sprintf(
      "mean flipper length: %0.2f",
      mean(dat$flipper_standardized)),
    side = 1, line = 5)
  mtext(
    sprintf(
      "fipper length standard deviation: %0.2f",
      sd(dat$flipper_standardized)),
    side = 1, line = 7)
  dev.off()
}



```

# 95% Critical z values

```{r, eval = FALSE}

png(filename = file.path(figure_dir,"standard_norm_z_95_pct_interval.png"), res = 190, width = 1500, height = 750)
gg_norm_conf_int(alpha = 0.05, title_fmt = "Standardized sampling distribution of the mean",
                 arrow_label_fmt = "$%1$0.2f \\pm %2$0.2f \\times SE$", x_lab = "z", y_lab = TeX("$f(z)$"))
dev.off()

```



# Z-standardization

```{r, eval = FALSE}
{
  
  fill_1 = rgb(0, 0.3, 0.8, 0.25)
  fill_2 = rgb(0, 0.8, 0.3, 0.25)
  
  x_min = -8
  x_max = 20
  
  len = 1800
  
  sd_1 = 2.1
  mean_1 = 11
  
  tt = theme(
    axis.title = element_blank())
  
}

{
  n_dat_1a = mfn.teaching.utils::build_dnorm_dat(xmin = x_min, xmax = x_max, len = len, pop_mean = mean_1, pop_sd = sd_1)
  n_dat_1b = mfn.teaching.utils::build_dnorm_dat(xmin = x_min, xmax = x_max, len = len, pop_mean = 0, pop_sd = sd_1)
  n_dat_2 = mfn.teaching.utils::build_dnorm_dat(xmin = x_min, xmax = x_max, len = len, pop_mean = 0, pop_sd = 1)
}

head(n_dat_1a)

{
  g_1 = ggplot() + tt +
    geom_line(aes(x = x, y = y1), data = n_dat_1a) + 
    geom_ribbon(aes(x = x, ymin = y0, ymax = y1), data = n_dat_1a, fill = fill_1) +
    geom_line(aes(x = x, y = y1), data = n_dat_2) +
    geom_ribbon(aes(x = x, ymin = y0, ymax = y1), data = n_dat_2, fill = fill_2)
  
  g_2 = ggplot() + tt +
    geom_line(aes(x = x, y = y1), data = n_dat_1b) + 
    geom_ribbon(aes(x = x, ymin = y0, ymax = y1), data = n_dat_1b, fill = fill_1) +
    geom_line(aes(x = x, y = y1), data = n_dat_2) +
    geom_ribbon(aes(x = x, ymin = y0, ymax = y1), data = n_dat_2, fill = fill_2)
  
  g_3 = ggplot() + tt +
    geom_line(aes(x = x, y = y1), data = n_dat_2) + 
    geom_ribbon(aes(x = x, ymin = y0, ymax = y1), data = n_dat_2, fill = fill_1) +
    geom_line(aes(x = x, y = y1), data = n_dat_2) +
    geom_ribbon(aes(x = x, ymin = y0, ymax = y1), data = n_dat_2, fill = fill_2)
}


png(filename = file.path(figure_dir,"z_standardization.png"), res = 190, width = 3000, height = 800)
cowplot::plot_grid(g_1, g_2, g_3, nrow = 1)
dev.off()

png(filename = file.path(figure_dir,"z_standardization_reverse.png"), res = 190, width = 3000, height = 800)
cowplot::plot_grid(g_3, g_2, g_1, nrow = 1)
dev.off()


```

