---
title: "ECo 602 - Analysis of Environmental Data"
subtitle: "Week 02 reading questions"
author: "Michael France Nelson"
date: "Fall 2020"
output:
  # pdf_document:
  #   toc: true
  #   number_sections: TRUE
  html_document:
    theme: readable
    css: !expr here::here("formatting", "css", "eco_602_2020.css")
    toc: TRUE
    toc_float: TRUE
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```


```{r build_questions, eval= FALSE, echo = FALSE}
require(rmd.utils)
source(find_file("gather_assignment_paths.R"))
source(find_file("build_lab.R"))

build_reading_questions(2, moodle_xml = FALSE)
```



This reading assignment covers materials from the following week 1 and week 2 readings:

- Epstein: Why Model?
- McGarigal ch. 1
- Bolker Chapter 1: sections 1.1, 1.2, 1.3
- McGarigal Chapter 2

And the lecture:

- Model Thinking 1: What is a Model?



# Questions

