---
title: "ECo 602 - Analysis of Environmental Data"
subtitle: "Distribution Functions"
author: "Michael France Nelson"
date: "Fall 2020"
output:
  beamer_presentation:
    pandoc_args: !expr paste0(here::here("formatting", "beamer", "eco_602_2020_beamer.yaml"))
    highlight: tango
    theme: "default"
    colortheme: "spruce"
    fonttheme: "serif"
    slide_level: 2
    incremental: false
classoption: t
header-includes:
  \input{`r here::here("formatting", "beamer", "eco_602_2020_headers_tikz.tex")`}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")
require(rmd.utils)
# require(ggplot2)
# require(mfn.teaching.utils)

```





## Key Distributions Terms and Concepts

- Theoretical and empirical distributions
- Parameters
- Distribution functions
  - Probability Density/Mass
  - Cumulative Density/Mass
  - Quantile Functions




```{r child = find_file("distribution_functions_concepts.Rmd")} 
```





## Recap

- Theoretical and empirical distributions
- Parameters
- Distribution functions
  - Probability Density/Mass
  - Cumulative Density/Mass
  - Quantile Functions

